### ISSUE TITLE
Add README to explain how this works

### ISSUE THREAD

**Issue by justwheel** [CraftSpider/PySecurityManager#1]
Hi, I thought this was a neat project! Do you think you could put together a README to explain your code or how it works, versus a 3.7 way of doing something like this? It would be cool to help me understand how this feature works! :smile:

**Comment by CraftSpider** [comment]
Added a README, with notes on how I'd replicate in 3.7. Feel free to open another issue if you think I missed something!

**Comment by justwheel** [comment]
Awesome, thanks! :raised_hands:
